### ISSUE TITLE
Need the F:\AZ300\Labs\03\template03.json file mentioned in the lab steps 

### ISSUE THREAD

**Issue by DDHudson** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#1]
Need the F:\AZ300\Labs\03\template03.json file mentioned in the lab steps AZ-300T01A

**Comment by DDHudson** [comment]
This is no longer an issue.    The file has been provided.

**Comment by DDHudson** [comment]
Done!

**Comment by KindReality** [comment]
Thank you Delores!
