### ISSUE TITLE
AZ-300T01_Lab_Mod05 error in instructions

### ISSUE THREAD

**Issue by melvinchia** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#100]
Exercise 1 Instruction 7:

`az group deployment create --resource-group az3000501-LabRG --template-file azuredeploy05.json --parameters @azuredeploy05.parameters.json`

Ends with an error. Resolved by removing the @ in the command.

`az group deployment create --resource-group az3000501-LabRG --template-file azuredeploy05.json --parameters azuredeploy05.parameters.json`

**Comment by polichtm** [comment]
What is the error you are getting?
rgds
Marcin

**Comment by melvinchia** [comment]
Running in bash shell doesn't churn any errors, but it doesn't run successfully.
Running in PowerShell churns the following error, and it stops running.

`The splatting operator '@' cannot be used to reference variables in an expression. '@azuredeploy05.parameters.json' can be used only as an argument to a command. To reference variables in an expression use '$azuredeploy05.parameters.json'.`

**Comment by melvinchia** [comment]
The same type of error happens when following the instructions in AZ-300T02_Lab_Mod03.

Exercise 1 Task 1.7
`az group deployment create --resource-group az3000401-LabRG --template-file azuredeploy0401.json --parameters @azuredeploy04.parameters.json --no-wait`

Exercise 2 Task 2.2
`az group deployment create --resource-group az3000402-LabRG --template-file azuredeploy0402.json --parameters @azuredeploy04.parameters.json --no-wait`

In both cases, removing the @ from the command line parameters works in both bash shell and PowerShell. Error when following what's on the instructions.

**Comment by polichtm** [comment]
Pls make sure to follow the lab instructions. 
This is meant to be run from the Bash shell
rgds
Marcin

**Comment by melvinchia** [comment]
I did.. I ran it during class in Bash shell, didn't work.. Couldn't proceed with the lab.

Then the guy sitting next to me told me he was using PowerShell and it highlighted the @ error. And that it worked without the @ in his case.

I removed the @ from my Bash shell command and was able to proceed with the lab.

**Comment by polichtm** [comment]
Pls provide the error message. 
In addition, refer to https://docs.microsoft.com/en-us/cli/azure/group/deployment?view=azure-cli-latest#az-group-deployment-create
rgds
Marcin

**Comment by melvinchia** [comment]
just tried it again today, seems it works today but not day before yesterday and yesterday; i'm a bash shell user.. so idk what happened.. maybe something intermittent/random.. closing this issue..
