### ISSUE TITLE
AZ-300T03_Lab_Mod03_Implementing Azure Load Balancer Standard.md error

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#103]
Ex 1 Task 1 Step 7: Get DSC error during deployment. The error comes from a spurious @ in the command before the parameter file

--

**Comment by polichtm** [comment]
Pls post the error message
rgds
Marcin

**Comment by begler1** [comment]
![Screenshot (4653)](https://user-images.githubusercontent.com/22414394/66084248-2995ea80-e53c-11e9-9af4-55604b24cc86.png)
