### ISSUE TITLE
Part 06 Mod 01 - UI inconsistency

### ISSUE THREAD

**Issue by derhoppe** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#106]
Part 06 module 01 Lab: UI inconsistency in Excercise 1 from step 13 onwards. The portal UI has changed.

**Comment by polichtm** [comment]
Would you mind clarifying which lab you are referring to?
rgds
Marcin

**Comment by polichtm** [comment]
updated
