### ISSUE TITLE
AZ-300T02_Lab_Mod01: Mismatch between title and content?

### ISSUE THREAD

**Issue by lp-code** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#107]
The AZ-300T02_Lab_Mod01 lab has the title "Evaluating and Performing Server Migration to Azure".
The subtitle is then "Implementing Azure to Azure migration", so it is no longer migrating _to_ Azure (which sounds like using Azure Migrate) that is the goal. The content of the tutorial then shows how to replicate a VM to a recovery services vault, which to me is a third thing.
Now, you may say the replicated VM is a migrated version of the original one, but that point is not made anywhere in the tutorial. 
Am I missing something here?

**Comment by polichtm** [comment]
As far as I can tell, this is the simplest approach to illustrating the basic ASR functionality (which single Azure VM replication relies on). Are you looking for something more elaborate (and if so, do you have anything in particular in mind) - or are you simply asking to include a note that would indicate that a failover of a replicated VM (without failing it back) could be considered an example of server migration? 
rgds
Marcin

**Comment by lp-code** [comment]
It's true that it is a nice example of site recovery -- so why not call it like that in the title?

**Comment by polichtm** [comment]
"Evaluating and Performing Server Migration to Azure" is the name of the corresponding course module. 
The name of the lab is "Implementing Azure to Azure migration"
rgds
Marcin

**Comment by polichtm** [comment]
let us know if you have any other comments/questions
