### ISSUE TITLE
Z-300T06_Lab_Mod01: bash openssl rand has wrong params

### ISSUE THREAD

**Issue by bjs169** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#109]
In two place the following command is given:

PREFIX=$(echo `openssl rand **_5 -base64_** . . . . 

This is not correct.

Correct is:

PREFIX=$(echo `openssl rand **_-base64 5_** . . . .

**Comment by bjs169** [comment]
You missed one. There are two places in the file where this issue occurs. You fixed the first.

**Comment by polichtm** [comment]
updated
