### ISSUE TITLE
AZ-300T01_Lab_Mod05_Implementing user-assigned managed identities

### ISSUE THREAD

**Issue by shkumesh** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#110]
Exercise 2:
7. From the PowerShell prompt, run the following to install the the pre-release version of the PowerShellGet module:

Install-Module -Name PowerShellGet -AllowPrerelease

This is not working.

![error_vm1](https://user-images.githubusercontent.com/48082518/67928038-18460980-fbe0-11e9-863d-fd874e25e1e5.PNG)

**Comment by polichtm** [comment]
updated
