### ISSUE TITLE
AZ-300T01_Lab_Mod05_Implementing user-assigned managed identities

### ISSUE THREAD

**Issue by shkumesh** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#111]
Exercise 2: Validating functionality of user-assigned managed identities

5. Switch back to the Remote Desktop session, and, from the PowerShell prompt, run the following to attempt to retrieve the currently used managed identity:

(Get-AzVM -ResourceGroupName az3000501-LabRG -Name az3000501-vm).Identity

This was not worked with the reader role and I had to use contributor role

![error_vm2](https://user-images.githubusercontent.com/48082518/67932062-3a905500-fbe9-11e9-87d3-0047cda8a050.PNG)

![error_vm3](https://user-images.githubusercontent.com/48082518/67932131-61e72200-fbe9-11e9-8e6e-767ccbfc8473.PNG)

**Comment by polichtm** [comment]
Excercise 1, Task 1, Step 1 states:
From the lab virtual machine, start Microsoft Edge and browse to the Azure portal at http://portal.azure.com and sign in by using the Microsoft account that has the Owner role in the target Azure subscription.
rgds
Marcin

**Comment by polichtm** [comment]
Exercise 1, Task 3, step 3 states:
1. From the **az3000502-LabRG - Access control (IAM)** blade, assign the Owner role to the newly created user-assigned managed identity.
rgds
Marcin

**Comment by polichtm** [comment]
updated
