### ISSUE TITLE
Typo in AZ-300T03_Lab_Mod04 instructions

### ISSUE THREAD

**Issue by aliadnanmalik** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#117]
**In Section 3 - When removing the Resource Group
Quote in the wrong place on Task 1, Step 3 and Task 2, Step 1**

**Task 1, Step 3** 
Code illustrates: 
`az group list --query "[?starts_with(name,'az30009')]".name --output tsv`

Should be
`az group list --query "[?starts_with(name,'az30009')].name" --output tsv`

**Task 2, Step 1**
Code illustrates: 
`az group list --query "[?starts_with(name,'az30009')]".name --output tsv | xargs -L1 bash -c 'az group delete --name $0 --no-wait --yes'`

Should be
`az group list --query "[?starts_with(name,'az30009')].name" --output tsv | xargs -L1 bash -c 'az group delete --name $0 --no-wait --yes'`

**Comment by polichtm** [comment]
Would you mind clarifying what specifically is the issue you are running into with the current commands?
rgds
Marcin

**Comment by aliadnanmalik** [comment]
as mentioned the quote is in the wrong place: 
`".name
`
Should be 
`.name"`
______________________
Output:
```
PS Azure:\> az group list --query "[?starts_with(name,'az30009')]".name --output tsv
az group list: error: argument --query: expected one argument
usage: az group list [-h] [--verbose] [--debug]
                     [--output {json,jsonc,table,tsv,yaml,none}]
                     [--query JMESPATH] [--subscription _SUBSCRIPTION]
                     [--tag [TAG]]
```

**Comment by polichtm** [comment]
It appears that you are running this from the PoweShell prompt. 
The instructions state "
If needed, switch to the Bash shell session by using the drop down list in the upper left corner of the Cloud Shell pane."
rgds
Marcin

**Comment by aliadnanmalik** [comment]
Ah got it Thanks. Apologies for inconvenience.

**Comment by polichtm** [comment]
np
