### ISSUE TITLE
unclear steps in exercise T04 Lab Mod 01

### ISSUE THREAD

**Issue by derhoppe** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#120]
In Exercise 2, Task 2, Step 8 instead of 

"To: the name of your Microsoft Account"

it should be

"To: the email address of your Microsoft Account"

rgds, Sebastian

**Comment by polichtm** [comment]
Hi Sebastian,
Do you mean the primary alias of the Microsoft Account? A Microsoft Account can have up to 10 email addresses associated with it.
Marcin

**Comment by derhoppe** [comment]
Hi Marcin,

for students the instruction is kind of unclear, because they often can't associate "Microsoft Account" to "E-Mail Address". So perhaps the statement could be "To: the primary e-mail address of your Microsoft Account"

rgds, Sebastian

**Comment by polichtm** [comment]
Hi Sebastian
updated
rgds
Marcin
