### ISSUE TITLE
Routing and Remote Access in T04 Lab 01

### ISSUE THREAD

**Issue by Williams-Nest** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#121]
In T04 Lab 1 (Configuring VNet peering and service chaining) there is an installation of the Server Role "Routing and Remote Access" in Exercise 3, Task 3, Step 3-7, but this role is never used in any way in this lab.

Is there any reason for these steps when it is not used???

**Comment by polichtm** [comment]
Hi Michael,
I assume you are referring to T02 (AZ-300T02_Lab_Mod03_Configuring VNet peering and service chaining.md). 
The purpose of configuring routing on az3000401-vm2 is to illustrate that the traffic to 10.0.0.4 is actually routed via 10.0.1.4 (Exercise 4, Task 2, Step 4). Let me know if this is still not clear to you.
rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response
