### ISSUE TITLE
typos in AZ-300T04_Lab_Mod01_Implementing Azure Logic Apps exercise

### ISSUE THREAD

**Issue by jungylee1101** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#125]
when deleting lab resources in Exercise 3, both command lines aren't correct which throw an error on powershell. 

A double quotation needs to come after .name but it comes after a square bracket as you can see below;  

az group list --query "[?starts_with(name,'az30007')]".name --output tsv. 

az group list --query "[?starts_with(name,'az30007')]".name --output tsv | xargs -L1 bash -c 'az group delete --name $0 --no-wait --yes'

**Comment by polichtm** [comment]
These are not PowerShell cmdlets - pls make sure to run them from the Bash shell - as specified in the instructions
rgds
Marcin
