### ISSUE TITLE
Question regarding 300T02_Lab_Mod03, parameters with @? (NOT an issue!)

### ISSUE THREAD

**Issue by Cyberman-tM** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#133]
It probably is used elsewhere as well, and it's likely something everyone but me knows, unfortunately google is in this case useless (a quick search in bing didn't show anything useful either).

Why is there an @ in front of the actual value for the --parameters parameter?
Example:

az group deployment create --resource-group az3000401-LabRG --template-file azuredeploy0401.json --parameters @azuredeploy04.parameters.json --no-wait

The best I could find was that it's to mark the file as local, but then why isn't the first file marked as well?
The documentation seems to be silent about it - it uses it as well. Is it a bash special character?

**Comment by polichtm** [comment]
Pls refer to https://docs.microsoft.com/en-us/cli/azure/group/deployment?view=azure-cli-latest#az-group-deployment-create
rgds
Marcin
