### ISSUE TITLE
AZ-300T01_Lab_Mod05 - install-module failures

### ISSUE THREAD

**Issue by DaveMcCloud** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#138]
Due to the recent changes you need to run 
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
prior to any install-module commands.  This needs to be run twice in the lab as it doesn't persist after the restart of powershell.

**Comment by polichtm** [comment]
updated

**Comment by molenaar** [comment]
@polichtm, we MCTs are discovering these failure in all the Azure and M365 courses. Not all repositories are maintained that well (especially the M365 one). Can you make sure other maintainers of the Microsoft learning repositories are award of this necesary (tls2) update?
Lets keep eachother informed. Save a lot of time troubleshooting during class for MCTs

**Comment by polichtm** [comment]
Hi Marcel, 
unfortunately I have no direct contact with those who maintain these repos. Let me see what can be done in this case
rgds
Marcin
