### ISSUE TITLE
AZ-300T03_Lab_Mod04_Implementing custom Role Based Access Control roles

### ISSUE THREAD

**Issue by Franlusan** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#139]
In exercise 1 Task 3 "Create a custom RBAC role in an Azure AD tenant" step 20. I RUN THE COMMAND IN Azure PShell 
$subscription_id = (Get-AzContext).Subscription.id AND THEN
(Get-Content -Path $HOME/customRoleDefinition09.json) -Replace 'SUBSCRIPTION_ID', "$subscription_id" | Set-Content -Path $HOME/customRoleDefinition09.json AND IT IS FINE BUT
THEN I RUN THE NEX COMMAND IN STEP 21
New-AzRoleDefinition -InputFile $HOME/customRoleDefinition09.json bBUT IT APPEARS THIS ERROR:
New-AzRoleDefinition: Scope '/subscriptions' should have even number of parts.
MAYBE I AM NOT WRITING THE CORRECT SYNTAX OR THE EXERCISE IS WRONG. CAN YOU HELP ME, PLEASE?

**Comment by polichtm** [comment]
Can you confirm that you are an MCT?
rgds
Marcin

**Comment by Franlusan** [comment]
Yes, I am. MCP ID 2486476. Anyway I have found a solution for the issue. What I have done is edit customRoleDefinition09.json file and change SUBSCRIPTION_ID in the last row by my real Subscription ID. Then everything goes well. Step 20 might do the same but I get the same error I explained in the first message. Step 19 should be put before the .json file.

**Comment by Franlusan** [comment]
Also it seems strange to me that I can create a Custom RBAC role using PShell and when I try to do it using the GUI "Roles and administrators" it says that I need a Premium 1 or 2 licence.

**Comment by polichtm** [comment]
Good to see that you managed to get your issue resolved.
Fyi - that replacement should have happened when you run
$subscription_id = (Get-AzContext).Subscription.id
(Get-Content -Path $HOME/customRoleDefinition09.json) -Replace 'SUBSCRIPTION_ID', "$subscription_id" | Set-Content -Path $HOME/customRoleDefinition09.json

I'm not in the position to comment on Microsoft's marketing decisions - but your feedback is appreciated

rgds
Marcin
