### ISSUE TITLE
AZ-300T01_Lab_Mod01 Name too long

### ISSUE THREAD

**Issue by djcmct** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#14]
Ex 1 Task 1 Step 3 requires input of Vmss name, specified value of az01-vmss-[your name in lowercase here] is far too long for permitted maximum 9 characters.

As this has to be unique as a public DNS alias, could I suggest that the format of initials followed by the date in ddmmyy (or mmddyy if preferred by our American colleagues) be used instead,
e.g. djc260219

unfortunately, all other references to the name in the instructions would also have to be replaced.

**Comment by polichtm** [comment]
appreciate the suggestion - I opted for using Test-AzDnsAvailability 
Let us know if this works for you
rgds
Marcin

**Comment by djcmct** [comment]
worked fine, the validation stage does verify before attempting to create but wouldn't do any harm to include the Test-AzDnsAvailability to make sure

**Comment by polichtm** [comment]
;)

**Comment by molenaar** [comment]
Some additional info, enhancements and tips;

>is far too long for permitted maximum 9 characters

Far too long? The domainNameLabel property for public IP addresses must be unique. The domainNameLabel value must be between 3 and 63 characters long.
https://docs.microsoft.com/en-us/azure/azure-resource-manager/template-best-practices

The VM name should be between 1 and 15 length for windows or between 1 and 64 for linux vms
https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions#naming-rules-and-restrictions

That why I also suggested to modify the ARM Template: https://github.com/MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies/pull/12

> go to edit template and modify at line 98:
> `[parameters('vmssName')]`
> into
> `[concat(parameters('vmssName'), uniqueString(resourceGroup().id)]`


The Test-AzDnsAvailability option is also a good way to check if any chosen name is available.

To generate a unique prefix (like uniquestring in ARM) you can also use powershell to generate your own unique string for the course, based on the subscription id:
`((Get-AzureRmSubscription).id).Substring(0,8)`

Arm Templates often use a unique string based on the resourcegroup id, however before initiating the ARM template in this lab, a resource group isn't available yet. 

So the name of the vm, used in the lab before, could be:
`"az01-vmss-"+((Get-AzureRmSubscription).id).Substring(0,8)`

https://www.codeisahighway.com/use-uniquestring-function-to-generate-unique-names-for-resources-in-arm-template/

**Comment by djcmct** [comment]
As this value is used as a base for naming other resources, if it was greater than 9 characters violate any permitted lengths of any resource it was used to form the name of?
