### ISSUE TITLE
issue at AZ-300T03, module 5 lab "Implementing Secure Data"

### ISSUE THREAD

**Issue by Franlusan** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#140]
In the exercise 2 "Set and retrieve a secret from Azure Key Vault using PowerShell" when arriving to the command 3 "Set-AzKeyVaultSecret" I get the error "Forbidden" and cannot continue. Previously, as you can see in the Capture there is a WARNING because there are no Vault Policies Set.
I think there is a command missing perhaps. Could you help me with this it please? Thank you

**Comment by polichtm** [comment]
Pls consult with your MCT
rgds
Marcin
