### ISSUE TITLE
Set and retrieve a secret from Azure Key Vault using PowerShell

### ISSUE THREAD

**Issue by Franlusan** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#142]
Hello again. Sorry for the last issue. I did not explain it correctly. 
I am trying to Set and retrieve a secret from Azure Key Vault using PowerShell and this is what I do:
1.- New-AzResourceGroup -Name ContosoResourceGroup  -Location EastUS
2.- New-AzKeyVault -Name 'Contoso-Vault2' -ResourceGroupName 'ContosoResourceGroup' -Location 'East US'
3.- $secretvalue = ConvertTo-SecureString 'hVFkk965BuUv' -AsPlainText -Force
At this point a WARNING appears informing me that no Policies have been set but lets me continue
4.- $secret = Set-AzKeyVaultSecret -VaultName 'ContosoKeyVault' -Name 'ExamplePassword' -SecretValue $secretvalue
But it gives me an error "Access is forbidden"
I thing the error is related to the Warning but I do not know what is the command missing.
Could you help me with this Please? Regards

**Comment by renaudwangler** [comment]
Hello. Please, could you tell us what lab number is your concern related to ? This information would hepl anyone to understand your concern !

**Comment by Franlusan** [comment]
Hi
I have created another issue where I explain better the situation
I want to Set and retrieve a secret from Azure Key Vault using PowerShell
So first I create a RG
New-AzResourceGroup -Name PACORG -Location EastUS            OK
Then I create a KeyVault
New-AzKeyVault -Name 'PACOVAULT222' -ResourceGroupName 'PACORG' -Location 'East US'
And I get this warning “WARNING: Access policy is not set. No user or application have access permission to use this vault. This can happen if the vault was created by a service principal. Please use Set-AzKeyVaultAccessPolicy to set access policies”
I continue to create a secret and type:
$secretvalue = ConvertTo-SecureString 'hVFkk965BuUv' -AsPlainText -Force     and it is OK
And this to create a secret in Key Vault called ExamplePassword with the value hVFkk965BuUv
$secret = Set-AzKeyVaultSecret -VaultName 'ContosoKeyVault' -Name 'ExamplePassword' -SecretValue $secretvalue
AND HERE IS THE ERROR
Set-AzKeyVaultSecret: Operation returned an invalid status code 'Forbidden'
I THINK THE ERROR HAS SOMETHING TO DO WITH THE PREVIOUS WARNING but I do not know how to fix it.
I am the owner of the subscription so I should have all the permissions on all the objects
I do not understand it
I would appreciate your help
Regards

Francisco Luque Santiago
http://www.franciscoluque.com<http://www.franciscoluque.com/>    http://www.tuaulavirtual.es<http://www.tuaulavirtual.es/>
MCSE, Trainer Windows, Security, Exchange, Hyper-V, SCCM, Office 365, Azure administrator
PeopleCert ITIL 4 Accredited Trainer, Traductor técnico inglés- francés-español
Skype: jf.luque


De: renaudwangler <notifications@github.com>
Enviado el: martes, 21 de abril de 2020 12:08
Para: MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies <AZ-300-MicrosoftAzureArchitectTechnologies@noreply.github.com>
CC: Franlusan <jf.luque@outlook.com>; Author <author@noreply.github.com>
Asunto: Re: [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies] Set and retrieve a secret from Azure Key Vault using PowerShell (#142)


Hello. Please, could you tell us what lab number is your concern related to ? This information would hepl anyone to understand your concern !

**Comment by renaudwangler** [comment]
I guess your error is not at all related with your warning: in your "Set-AzKeyVaultSecret" command, you refer a key vault named "ContosoKeyVault" but in your previous command you created a key vault with another name (PACOVAULT222). 
PS : I still don't understand the relation with the labs...

**Comment by Franlusan** [comment]
Sorry, I made a mistake on the mail.
In the reality I did write PACOVAULT222

**Comment by polichtm** [comment]
Pls consult with your MCT
rgds
Marcin

**Comment by Franlusan** [comment]
Francisco Luque Santiago
http://www.franciscoluque.com<http://www.franciscoluque.com/>    http://www.tuaulavirtual.es<http://www.tuaulavirtual.es/>
MCSE, Trainer Windows, Security, Exchange, Hyper-V, SCCM, Office 365, Azure administrator
PeopleCert ITIL 4 Accredited Trainer, Traductor técnico inglés- francés-español
Skype: jf.luque

Hello Marcin
I am MCT.
It seems some labs in Azure course AZ-300 are not correct.
I thought GitHub may help me.
Regards

De: polichtm <notifications@github.com>
Enviado el: jueves, 23 de abril de 2020 2:34
Para: MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies <AZ-300-MicrosoftAzureArchitectTechnologies@noreply.github.com>
CC: Franlusan <jf.luque@outlook.com>; Author <author@noreply.github.com>
Asunto: Re: [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies] Set and retrieve a secret from Azure Key Vault using PowerShell (#142)


Pls consult with your MCT
rgds
Marcin

**Comment by polichtm** [comment]
Hi Francisco, 
appreciate the clarification.
Pls provide the lab number, exercise number, task number and step number that you are referring to
rgds
Marcin

**Comment by Franlusan** [comment]
Hello Marcin
I had to skip that lab to continue 
Maybe I will come back later with this
Thanks anyway

**Comment by polichtm** [comment]
np
rgds
Marcin
