### ISSUE TITLE
AZ-300T01_Lab_Mod01: Deploy to Azure button workaround and VMSize issue

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#143]
AZ-300T01_Lab_Mod01: Deploy to Azure button workaround and VMSize issue:
--
Ex 1   Task 1 Steps 7 and 8: If Deploy to Azure button fails: Alternate workaround instructions: "In the   upper left corner of the Azure portal, click Create a resource. At the top of the New blade, in the   Search the Marketplace text box, type Template and in the search results, click Template   Deployment (deploy using custom templates). On the   Template deployment blade, click the Create button. On the Custom deployment blade, under Load a GitHub quickstart template,   click the drop-down list and then enter 201-vmss-bottle-autoscale. Scroll-down then click Select   template." Continue with Step 9.
Ex 1   Task 1 Step 9: "Vm Sku: Standard_D1_v2" should be "Vm Sku: Standard_D2s_v3" when using Azure Pass. 
Ex 1   Task 2 Step 3: Update Scale rules "Scale out: increase instance count by   1 when average percentage of CPU > 40" and "Scale in: decrease instance count by 1 when   average percentage of CPU < 20" and "Maximum number of instances: 3". Save your changes.
Ex 2   Task 1 Step 12: "set the threshold to 60" should be "set the   threshold to 40"
Ex 2   Task 1 Step 14: "set the alert rule name to Percentage CPU of the VM  scale set is greater than 40   percent"

**Comment by polichtm** [comment]
updated
