### ISSUE TITLE
AZ-300T01_Lab_Mod03: VMSize issue with Azure Pass

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#144]
AZ-300T01_Lab_Mod03: VMSize issue with Azure Pass:
--
Ex 2   Task 1 Step 1: Error: image not available: fix: append the following to the   deployment command for Azure Pass: --size Standard_D2s_v3

**Comment by polichtm** [comment]
updated
