### ISSUE TITLE
Incorrect Markdown Syntax

### ISSUE THREAD

**Issue by rlthompson904** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#145]
It appears that the square brackets are not being escaped properly via \[ and \] per the GitHub Markdown standard found here https://github.github.com/gfm/#backslash-escapes. This can cause text within square brackets to not be rendered if cloned and viewed outside of the raw markdown.

**Comment by polichtm** [comment]
Pls clarify which lab/exercise/task/step you are referring to 
rgds
Marcin

**Comment by begler1** [comment]
Ex 2 Task 1: Step 4 and Step 7

**Comment by polichtm** [comment]
Pls clarify which lab you are referring to
rgds
Marcin

**Comment by begler1** [comment]
It's the lab from AZ300T01 Module 5 Managing Identities.

**Comment by polichtm** [comment]
That's part of the code. 
What exactly is the rendering issue you are seeing and in what scenario?
rgds
Marcin

**Comment by begler1** [comment]
This can cause text within square brackets to not be rendered if cloned and viewed outside of the raw markdown.

**Comment by polichtm** [comment]
Unfortunately it's still not clear to me what specific scenario you are referring to. 
Can you describe what is the exact issue you are running into and what is the change you are recommending?
rgds
Marcin

**Comment by polichtm** [comment]
Closing due to lack of response
