### ISSUE TITLE
AZ-300T01 quickstart template has incomplete load balancer configuration

### ISSUE THREAD

**Issue by donbr** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#151]
The 201-vmss-bottle-autoscale template is missing the required configuration for the load balance probe and rule.

Is this intended to be a troubleshooting lab?

**Comment by polichtm** [comment]
Pls clarify which lab, exercise, task, and step you are referring to
rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response
