### ISSUE TITLE
Typo in Lab: Implementing Azure Load Balancer Standard

### ISSUE THREAD

**Issue by samdlinn** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#154]
In Exercise 2, Task 1, number 5, of  AZ-300T03_Lab_Mod03_Implementing Azure Load Balancer Standard.md there is a typo.

The command is `az deployment group create --resource-group az3000801-LabRG --template-file azuredeploy0802.json --parameters @azuredeploy0802.parameters.json`. 
It should be `az deployment group create --resource-group az3000801-LabRG --template-file azuredeploy0802.json --parameters azuredeploy0802.parameters.json`.

Simply needs to have the `@` symbol removed.

**Comment by polichtm** [comment]
Pls make sure to use Bash shell session - not PowerShell session - as per instructions
rgds
Marcin

**Comment by samdlinn** [comment]
I did, I had no problem completing this lab.
The issue is that the command is referencing a file called `@azuredeploy0802.parameters.json` not `azuredeploy0802.parameters.json` which is what the file is called. You'll notice it doesn't do that with other file names. 

Up to you guys if you want to fix it. 🤷

**Comment by polichtm** [comment]
Pls refer to https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/deploy-cli
"To pass a local parameter file, use @ to specify a local file named storage.parameters.json."
rgds
Marcin

**Comment by samdlinn** [comment]
Fair enough.

Thank you for taking the time to explain that.
