### ISSUE TITLE
AZ-300T06_Lab_Mod01 - UI has changed

### ISSUE THREAD

**Issue by elliotsegler** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#156]
Looks like reoccurance of #106.

The line at [AZ-300T06_Lab_Mod01_Configuring a Message-Based Integration Architecture.md#L140](https://github.com/MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies/blame/master/Instructions/AZ-300T06_Lab_Mod01_Configuring%20a%20Message-Based%20Integration%20Architecture.md#L140) isn't an option in the lab anymore.

> 1. On the **Function App runtime stack** blade, ensure that the **.NET** entry appears in the **Function Runtime stack** drop down list and click **Go**.

Additionally, the templates don't identify which runtime they use so you have to _guess_ which template to use. It's the last one at the time of writing this, although that's not a guarantee.

It'd be better to use the AZ cli until they fix the dissapointng UI issues.

**Comment by elliotsegler** [comment]
A command like below might be better around [L126](https://github.com/MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies/blame/master/Instructions/AZ-300T06_Lab_Mod01_Configuring%20a%20Message-Based%20Integration%20Architecture.md#L126)?
```
az functionapp create --name "${FUNCTION_NAME}" --resource-group "${RESOURCE_GROUP_NAME}" --storage-account "${STORAGE_ACCOUNT_NAME}" --consumption-plan-location "${LOCATION}" --runtime "dotnet"
```

**Comment by dpapkin** [comment]
Thanks @elliotsegler . It works. Just add --runtime "dotnet"  to the end of the "az functionapp create" command

**replace this** 

   az functionapp create --name "${FUNCTION_NAME}" --resource-group "${RESOURCE_GROUP_NAME}" --storage-account "${STORAGE_ACCOUNT_NAME}" --consumption-plan-location "${LOCATION}"
``

**with this**
   az functionapp create --name "${FUNCTION_NAME}" --resource-group "${RESOURCE_GROUP_NAME}" --storage-account "${STORAGE_ACCOUNT_NAME}" --consumption-plan-location "${LOCATION}" --runtime "dotnet"

AND

***SKIP this 1 line *************

1. On the **Function App runtime stack** blade, ensure that the **.NET** entry appears in the **Function Runtime stack** drop down list and click **Go**.

**Comment by polichtm** [comment]
updated
rgds
Marcin
