### ISSUE TITLE
jq processor not working as excepted in Lab_Mod03 Custom Azure VM image

### ISSUE THREAD

**Issue by tohov** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#157]
Instructions/AZ-300T01_Lab_Mod03_Implementing Custom Azure VM Images.md

all the command line **jq commands** are resulting an error similar to this: "parse error: Invalid numeric literal at line 1, column 6". Previous error is for the CLIENT_ID=$(echo $AAD_SP | jq -r .AppId) command. Tried to troubleshoot it myself by reading the jq manual, but no luck in resolving this. Please check if the problem is in the jq version or syntax.

**Comment by polichtm** [comment]
Hi Tommi
this works perfectly fine for me.
Are you sure you are using Bash shell?
![image](https://user-images.githubusercontent.com/10284906/83093972-8a93a500-a06e-11ea-9036-c3f077f60475.png)
rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response
