### ISSUE TITLE
AZ300T04Mod1

### ISSUE THREAD

**Issue by afrks** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#158]
Participant reports
Exercise 3: Remove lab resources
Task 1: Open Cloud Shell
az group list --query "[?starts_with(name,'az30007')]".name --output tsv
quotes should be after name
same about 

Task 2: Delete resource groups
At the Cloud Shell command prompt, type in the following command and press Enter to delete the resource groups you created in this lab
az group list --query "[?starts_with(name,'az30007')]".name --output tsv | xargs -L1 bash -c 'az group delete --name $0 --no-wait --yes'

**Comment by polichtm** [comment]
Pls make sure to use Bash shell - as per instructions
rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response
