### ISSUE TITLE
AZ-300T01_Lab_Mod01 instructions don't match interface

### ISSUE THREAD

**Issue by djcmct** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#16]
Exercise 2: Implementing monitoring and alerting by using Azure Monitor task 1 instructions don't match the interface and its all a bit confusing, maybe that's just me....

If you could replace with the following, it would make it easier to follow

Task 1: Create Azure VM scale set metrics-based alerts
In the Azure portal, navigate to the Monitor blade and, from there, switch to the Monitor - Metrics blade.

On the Monitor - Metrics blade, use the filter to display Avg Percentage CPU metric of your VM scale set resource.

Review the resulting chart and note the average percentage CPU within the last few minutes.

Select New Alert Rule

In the Create Rule page click the error under Condition:

Under Alert Logic type 60 in the Threshold box

Under Evaluation based on change Period (grain) to Over the last 1 Minutes

Leave all other settings at the default

Click Done

On the Create Rule page under Action Groups click Create New 

Action group name: az30001 action group

Short name: az30001

Subscription: the name of the Azure subscription you used in the previous exercise

Resource group: Default-ActivityLogAlerts (to be created)

Action name: az30001-email

Action type: Email/SMS/Push/Voice

Email/SMS/Push/Voice: an email address, a mobile phone number, or a phone number that you want to use to receive alerts generated by this rule, then select OK twice.

Note: If the action group doesn't appear under Action Groups, click select existing and select the one you just created.

On the Create Rule page under Alert Details. 

Alert rule name: Percentage CPU of az01-vmss is greater than 60 percent

Description: Percentage CPU of az01-vmss is greater than 60 percent

Severity: Sev 3

Enable rule upon creation: Yes

Note: It can take up to 10 minutes for a metric alert rule to become active

**Comment by polichtm** [comment]
appreciate the suggestion - we updated the instructions accordingly - let us know if this works for you.
rgds
Marcin
