### ISSUE TITLE
Errata in AZ-300T01_Lab_Mod01_Exploring Monitoring Capabilities in Azure.md

### ISSUE THREAD

**Issue by hawkism** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#162]
Line 131 - 
"set the action group name: **az30001-email**" should be "set the action name: **az30001-email**

Lines 97, 143, 147 - 
60 percent average CPU usage is too high of a threshold - scaling out never occurs and alerts never get fired
When "start worker" is running, CPU usage only ever hits 50%.
I recommend changing 60 percent to 40%.

**Comment by polichtm** [comment]
updated
