### ISSUE TITLE
Errata in AZ-300T03_Lab_Mod01_Implementing Azure Storage access controls.md

### ISSUE THREAD

**Issue by hawkism** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#165]
AZ-300T03_Lab_Mod01_Implementing Azure Storage access controls.md
Line 226:
az group list --query "[?starts_with(name,'az30002')]".name --output tsv

When executing this line in the Cloud Shell, the below error output is observed:
PS /home/steven_hawkins> az group list --query "[?starts_with(name,'az30002')]".name --output tsv
az group list: error: argument --query: expected one argument
usage: az group list [-h] [--verbose] [--debug] [--only-show-errors]
                     [--output {json,jsonc,yaml,yamlc,table,tsv,none}]
                     [--query JMESPATH] [--subscription _SUBSCRIPTION]
                     [--tag [TAG]]

**Comment by polichtm** [comment]
Pls make sure to use Bash shell - as described in the instructions
rgds
Marcin
