### ISSUE TITLE
Hi Mike - unfortunately I cannot reproduce he issue - let us know what you find out

### ISSUE THREAD

**Issue by MikeWilcoxMicrosoft** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#167]
Hi Mike - unfortunately I cannot reproduce he issue - let us know what you find out
rgds
Marin

_Originally posted by @polichtm in https://github.com/MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies/issues/166#issuecomment-648035402_

**Comment by MikeWilcoxMicrosoft** [comment]
Can the team please reopen my issue?  The problem still exists.. thank you

**Comment by polichtm** [comment]
Hi Mike, 
pls clarify what specifically the issue is by providing a reference to the lab, exercise, task, and step - and the steps to reproduce it
rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response
