### ISSUE TITLE
Resource group name convention ?

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#17]
What is the convention of the resource group names in the labs? 
The course is AZ-300, the days are AZ-300T01, AZ-300T02, .... The Modules are Module 01, 03, 05.
I am getting confused when I have to create a resource group: **az3000600-LabRG** in **300T02_Lab_Mod01**
https://github.com/MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies/blob/master/Instructions/AZ-300T02_Lab_Mod01_Implementing%20Azure%20to%20Azure%20migration.md

and **az3000400-LabRG** in **AZ-300T02_Lab_Mod03**
https://github.com/MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies/blob/master/Instructions/AZ-300T02_Lab_Mod03_Configuring%20VNet%20peering%20and%20service%20chaining.md

I guess we start with **00-LabRG or **01-LabRG and increment during the exercises.

**Comment by polichtm** [comment]
Hi Marcel,
the original convention clearly no longer matches the way the labs are currently organized. Adjusting the naming convention will be a bit more involved, since there are resource names and the corresponding scripts to consider. 
rgds
Marcin
