### ISSUE TITLE
AZ-300T01_Lab_Mod01_Exploring Monitoring Capabilities in Azure.md: New Alert Group UI change

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#171]
AZ-300T01_Lab_Mod01_Exploring Monitoring Capabilities in Azure.md: New Alert Group UI change:
--
Ex 2   Task 1 Step 6: 
"accept the default name of the resource group of   Default-ActivityLogAlerts (to be created), set the action name:   az30001-email, and set the action type to Email/SMS/Push/Voice." 
should be 
"accept the default name of the resource group, then in the **Notifications** pane, set the Name to **az30001-email**, and set the Notification type to **Email/SMS message/Push/Voice**."

Ex 2   Task 1 add to Step 7: Click **OK**.

Ex 2   Task 1 Step 8: "On the Add action group page, click OK." should be   "On the Create action group page, click **Review + Create**, and then click **Create**."

**Comment by polichtm** [comment]
updated
rgds
Marcin
