### ISSUE TITLE
AZ-300T01_Lab_Mod05 - Update powershell commands to use AZ module

### ISSUE THREAD

**Issue by djcmct** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#18]
To update lab to use new AZ commands, could you please replace with the following

Exercise 2 
Task 1

step 5
Install-Module -Name Az -AllowClobber

Step 8
Install-Module -Name Az.ManagedServiceIdentity -AllowPrerelease

Task 2

Step 1
Add-AzAccount -Identity

Step 2
(Get-AzVM -ResourceGroupName az3000501-LabRG -Name az3000501-vm).Identity

Step 5
(Get-AzVM -ResourceGroupName az3000501-LabRG -Name az3000501-vm).Identity

Step 6
$location = (Get-AzureRmResourceGroup -Name az3000502-LabRG).Location
New-AzPublicIpAddress -Name az3000502-pip -ResourceGroupName az3000502-LabRG -AllocationMethod Dynamic -Location $location

**Comment by polichtm** [comment]
I assume you meant:
Step 6
$location = (Get-AzRmResourceGroup -Name az3000502-LabRG).Location

**Comment by djcmct** [comment]
Thank you yes,

I'm just a simple techie trying to find my way in this new world of code ;)

**Comment by polichtm** [comment]
all good ;)
