### ISSUE TITLE
AZ-300T02_Lab_Mod01 - Update Powershell and simplify navigation

### ISSUE THREAD

**Issue by djcmct** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#19]
Update powershell to AZ module, replace following steps
Exercise 1
Task 1
Step 4
New-AzResourceGroup -Name az3000601-LabRG -Location <Azure region>

Step 7
New-AzResourceGroupDeployment -ResourceGroupName az3000601-LabRG -TemplateFile azuredeploy06.json -TemplateParameterFile azuredeploy06.parameters.json

To clarify instructions

Exercise 2
Step 1
Task 2
Replace the instruction - "Set the protection goal to Azure VMs to Azure" with "On the Overview page click +Replicate"

**Comment by polichtm** [comment]
completed
