### ISSUE TITLE
AZ-300T03_Lab_Mod03 - Update to Azure Load Balancer Portal interface

### ISSUE THREAD

**Issue by djcmct** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#21]
Think the portal must have been updated, the following steps match the new interface

Evercise 1 Task 2: Create an instance of Azure Load Balancer Standard
In the Azure portal, create a new Azure Load Balancer with the following settings:
Subsciption: the name of the target Azure subscription
Resource group: az3000801-LabRG
Name: az3000801-lb
Region: the name of the Azure region in which you deployed Azure VMs in the previous task of this exercise
Type: Public
SKU: Standard
Public IP address: Create new named az3000801-lb-pip01
Leave all other settings at the default and then create

Task 3
Step 4
On the Add backend pool blade, specify the following settings and click OK:
Name: az3000801-bepool
Associated to : Availability Set
Availability Set: az3000801-avset
Click + Add a target network IP configuration
Target Virtual Machine: az3000801-vm0 
Network IP Configuration: ipconfig1 (10.0.0.5)
Click + Add a target network IP configuration
Target Virtual Machine: az3000801-vm1
Network IP Configuration: ipconfig1 (10.0.0.4)
Note: It is possible that the IP addresses of virtual machines are asssigned in the reversed order.
Note: Wait for the operation to complete. This should not take more than 1 minute.

Task 3
Step 10
On the Add load balancing rule blade, specify the following settings and click OK:
Name: az3000801-lbrule01
IP Version: IPv4
Frontend IP address: select LoadBalancedFrontEnd
Protocol: TCP
Port: 80
Backend port: 80
Backend pool: az3000801-bepool (2 virtual machines)
Health probe: az3000801-healthprobe (TCP:80)
Session persistence: None
Idle timeout (minutes): 4
Floating IP (direct server return): Disabled

**Comment by polichtm** [comment]
This has been completed - pls note that, in general, we no longer follow the "click-through" format of the instructions. The intention is to encourage students to become familiar with the interface of the Azure portal, rather than have them simply follow very specific directions.
rgds
Marcin

**Comment by KindReality** [comment]
If we no longer follow the "click-through" format, we need to generalize the instruction so they aren't formatted in a "click-through" way.  That will help student familiarity. If the instructions are written in a "click-through" format for the old interface, we have out of date instructions.

**Comment by polichtm** [comment]
Hi Michael,
just to clarify - I'm not advocating for rewriting instructions. The challenge is that "generalizing" instructions might result in diminished clarity - and there is plenty of room of interpretation regarding what is considered to be "sufficiently clear". My intention is to address any potential issues as they come up in the incremental manner that hopefully we will be able to agree on.
rgds
Marcin
