### ISSUE TITLE
Json files for Lab Az300T02-Module3 in the wrong folder

### ISSUE THREAD

**Issue by ElaMark** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#3]
Whats wrong? The files azuredeploy0401.json, azuredeploy04.parameters.json, azuredeploy0402.json
should be in a folder called Module03, not Module02. The files that are currently in the folder Module03 shouldn't be there.

**Comment by polichtm** [comment]
resolved
