### ISSUE TITLE
AZ-300T03_Lab_Mod03 - Update to Azure Load Balancer Portal interface

### ISSUE THREAD

**Issue by Acoolio** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#34]
When Running the following in

az group deployment create --resource-group az3000801-LabRG --template-file azuredeploy0801.json --parameters @azuredeploy0801.parameters.json

Causes the following,  I removed the @ and it works. 

At line:1 char:111
+ ... plate-file azuredeploy0801.json --parameters @azuredeploy0801.paramet ...
+                                                  ~~~~~~~~~~~~~~~~
The splatting operator '@' cannot be used to reference variables in an expression. '@azuredeploy0801' can be used only as an argument to a command. To reference variables in an expression use '$azuredeploy0801'.
+ CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : SplattingNotPermitted

**Comment by polichtm** [comment]
Are you running this from a Bash session in Cloud Shell?
thnx
Marcin

**Comment by polichtm** [comment]
Closing due to lack of response.
