### ISSUE TITLE
Easily Import All Modules

### ISSUE THREAD

**Issue by mikedixson** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#35]
Use the following powershell to import all modules in your path. Modify path as necessary.
$pathToModules = "C:\Users\Administrator\Downloads\20533-ImplementingMicrosoftAzureInfrastructureSolutions-master\Allfiles\Modules"
Get-ChildItem -Path $pathToModules -Recurse | foreach {Import-Module $_.Fullname -Verbose}

**Comment by polichtm** [comment]
Hi Mike
This course does not include PowerShell modules
Presumably you're referring to 20533
rgds
Marcin
