### ISSUE TITLE
AZ-300T06 inconsistancy between slides and material

### ISSUE THREAD

**Issue by Williams-Nest** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#37]
In AZ-300T06 latest version from beginning of May 2019 - newly downloaded slides and book

Module 3 in Skillpipe is about Developing for Asynchronous Processing 
and the slides for that module is about development of App Service Logic App.

Module 5 in Skillpipe is about Developing Azure Cognitive Services Solutions
and the slides for that module is about Manage APIs using API Management

Module 6 in Skillpipe is about Develop for Azure Storage
and the slides for that module is Developing Azure Cognitive Services Solutions

The result is - I am missing slides for module 3 Developing for Asynchronous Processing 
and for module 6 Develop for Azure Storage

Besides - the labs are placed totally random

**Comment by polichtm** [comment]
We'll follow up regarding the content...
As far as labs are concerned, would you mind clarifying what you mean by "placed totally random"?
rgds
Marcin

**Comment by Williams-Nest** [comment]
AZ-300T01 Module 4, lesson 3 - in the slides the lesson starts with a "Practice" (Routing) 
But the practice is not shown anywhere else - and it is strange to place a practice in the beginning
AZ-300T02 Module 1, lesson 4, slide 35 and 36 shows practices that are not explained either.
There are many other "Practices" that are unexplained throughout all five days - but I need time to comment on all of them.

I also would like a more thorough explanation of the differences between "Practice" and "Online Lab"

**Comment by polichtm** [comment]
this has been resolved
rgds
Marcin
