### ISSUE TITLE
Spaces in Location variable cause an error

### ISSUE THREAD

**Issue by mikedixson** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#38]
**Exercise 1 task 5**
for example:
export LOCATION='<Azure_region>'  for UK South should be export LOCATION='UKSouth'

**Otherwise the following error occurs:**
Exercise 1 task 
for example:
export LOCATION='<Azure_region>'  for UK South should be export LOCATION='UKSouth'

**Comment by polichtm** [comment]
Hi Mike,
which lab are you referring to?
thnx
Marcin

**Comment by mikedixson** [comment]
Apologies, AZ-300T06_Lab_Mod01
https://github.com/MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies/blob/master/Instructions/AZ-300T06_Lab_Mod01_Configuring%20a%20Message-Based%20Integration%20Architecture.md

**Comment by polichtm** [comment]
updated
