### ISSUE TITLE
Spelling and other typos in the slides

### ISSUE THREAD

**Issue by Williams-Nest** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#41]
AZ-300 have some spelling and other issues.
We instructors have to use a lot of time to correct them before the course - and some spelling errors are unfortunately embedded as a picture.
Take AZ-300T02 module 1 slide 27. In the picture below "Coinfigure the infrastructure" - and this picture is used several places.
Take AZ-300T02 module 3 slide 18. In the top text "Application Gateway is a load balancer operating on OSI layer " - when asked we all know that it should be layer 7 - but I prefer to have the focus on the facts - not on some irrelevant typos.

**Comment by polichtm** [comment]
updates are in the works - more to follow...
rgds
Marcin

**Comment by polichtm** [comment]
updated
