### ISSUE TITLE
ExtremeLabs - Azure Passes not working

### ISSUE THREAD

**Issue by trazbyte** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#47]
When clicking on the link to "**Obtain Azure Pass**" my students and I receive a message "_Something Went Wrong. Unable to provide an Azure Pass at this time_"

**Comment by polichtm** [comment]
You might want to reach out to the contact person who provided you with Azure Pass keys
rgds
Marcin

**Comment by trazbyte** [comment]
Issue was resolved. Thanks
