### ISSUE TITLE
AZ300T01 Lab: Exploring Monitoring Capabilities in Azure

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#48]
Lab: Exploring Monitoring Capabilities in Azure
--

Ex 1   Task 1 Step 3: Click Show Advanced Settings first
Ex 1   Task 1 Step 3: Choose Create New for the Resource Group
Ex 1 Task 1 Step 3: Storage   account name must be unique: use intials and a 3 digit number e.g. sabe102
Ex 1 Task 1 Step 3: Fileshare   name: use intials and a 3 digit number e.g. fsbe102
Ex 1 Task 1 Step 4: For   instance, "East US" would be "eastus" (without quotes).
Ex 1   Task 1 Step 4: Name of VMSS will need to be unique, so use intials and a   number but note that you only have 9 chars to use. E.g. be102vmss.

**Comment by polichtm** [comment]
Appreciate the suggestions, but considering that this is an architecture course, we don't use the click-through approach - or at least we try to avoid it when the interface is very intuitive). 
I updated the instructions to account for your comments
rgds
Marcin
