### ISSUE TITLE
Lab T04 Mod 01 Logic App missing and incomplete steps

### ISSUE THREAD

**Issue by derhoppe** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#51]
Lab T04 Mod1 is missing a step in Exercise 2, "Task 2: Add an action to the Azure logic app" - need to add "Save Logic App" step

Step 8 of the same task does have errors "Event ID" should be "ID"

Exercise 2 Task 4 should be reviewed as the UI is slightly different than the description

**Comment by polichtm** [comment]
Which step in Exercise 2 Task 2 are you referring to? Is this step 8? If so, it already states that the app should be saved:
"In the Send an email pane, specify the following settings and click Save:"
updated the rest
