### ISSUE TITLE
Specific VM name referenced

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#53]
In file 'AZ-300T02_Lab_Mod03_Configuring VNet peering and service chaining.md' there are 3 references to a specific VM name 'MIA-CL1' (in Exercise 3/Task 3/Step 1, in Exer 4/Task 1/Step 1, and also in Exer 4/Task 2/Step 1)   Since there is no specific VM provided for this course the VM name of local or lab hosted VMs will vary and thus it may be good to use the generic/general reference here, as elsewhere in other instructions references.  

i.e., replace 'On MIA-CL1' with the generic reference 'From the lab virtual machine'

**Comment by polichtm** [comment]
updated
