### ISSUE TITLE
Confusing Error in AZ-300T04 Implementing Azure Logic Apps

### ISSUE THREAD

**Issue by XtremeDR** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#54]
In Exercise 2, Task 3, Step 1 the user is directed:

**In the Azure portal, navigate to the logicapp3000701 blade and, in the Summary section, click See trigger history.**

But the direction makes no note of what the user will expect to see there.  Going over this multiple times on each occasion I found an error indicating that the trigger had not run, simply giving the error message "Forbidden" and came to the conclusion that this error had to be resolved before moving forward.  The rest of the lab can be completed, and the error cleared up, but just continuing with the steps, but this error stopped me cold for hours before continuing on.  I would request a note be added to this task indicating the expected behavior of the "See Trigger History" or that users can ignore any errors and proceed onward.

**Comment by polichtm** [comment]
updated as requested
