### ISSUE TITLE
AZ-300T01_Lab_Mod01 Missing or incomplete text

### ISSUE THREAD

**Issue by derhoppe** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#56]
Text is partly missing or incomplete in Ex. 1 points 5 and 6

Verify that the command returned True. If not, rerun the same command with a different value o**f the until th**e command returns True.

Note the value **of the that r**esulted in the successful outcome. You will need it in the next task.

**Comment by polichtm** [comment]
updated
