### ISSUE TITLE
FIle Paths look incorrect

### ISSUE THREAD

**Issue by pdlab** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#6]
The file paths in the lab instructions don't match the repository given.
Example: F:\AZ300\Labs\03\template03.json

**Comment by polichtm** [comment]
Can you clarify what path are you expecting to see?
rgds
Marcin

**Comment by pdlab** [comment]
Shouldn't the file structure of this repository match the lab instruction file locations?

Lab instructions path = F:\AZ300\Labs\03\template03.json
Repository path = \allfiles\AZ-300T01\Module_03\template03.json

**Comment by polichtm** [comment]
I might be missing something, but I'd not expect students to access the GitHub repository directly. 
Where do your students access the lab files from? Aren't they local to the lab VM?
rgds
Marcin

**Comment by pdlab** [comment]
There is no supplied VM on the download center for this course.
We were told to use the current SEA-DEV VM with a few other software installs.
This VM does not have files in it for this course.

**Comment by polichtm** [comment]
I should've been more clear. I'd not expect for the VM image to include the lab files - that's obviously the very reason of having GitHub based repo. However, from what I understand, these files should be distributed as part of staging of the lab environment to lab VMs. 
rgds
Marcin

**Comment by KindReality** [comment]
pdlab, your concern is perfectly clear. Which machine you decide to use and downloading the files from git is obviously not at all related.  Everyone can see from your first question that there is a break in convention. Your second post makes it crystal clear. I see the repository uses the same ms conventions used for more than 15 years starting at the allfiles folder. The instructions do not. I see the repository uses the wrong folder name, AZ-300T01 and not \AZ300. I see that the instructions say labs and the repository says Module_3. As an MCT for 19 years, I am shocked at the handing on these newest courses, and I feel you pain and abandonment. The bad news is that you should expect much worse than this. Good luck, we need it.

**Comment by polichtm** [comment]
Just to clarify, I realize that there is currently a discrepancy between the relative path in the repo and the relative path in the instructions. My intention is to fix this discrepancy. 
What I'm trying to establish is whether the relative path would be sufficient - of whether we should update the path to point to a fully qualified path. 
If the consensus is that the relative path is sufficient - I'll update the instructions accordingly
rgds
Marcin

**Comment by KindReality** [comment]
I don't see how comments about the usage of a VM would have left us to understand you are working on a solution. I am glad you are. Thank you. I suggest a relative path consistently used based on MS conventions. My suggestion is  AZ-300T01\Labfiles, AZ-300T01\Demofiles, AZ-300T01\Tools ect... Sorry for my tone, but this is my first negative experience of this type and magnitude in nearly 20 years. If you have been with MS MOC for long enough, you understand something is very wrong. 300 and 301 are not ready, and other quality courses are gone!

**Comment by KindReality** [comment]
How does this happen? Obviously these steps have not been tested in any way as this aspect of the interface changed months before the course launched. .

**Comment by polichtm** [comment]
Unfortunately I don't have any details regarding how the discrepancy came about.
I'll gladly assist with getting it fixed.
rgds
Marcin

**Comment by polichtm** [comment]
this has been completed
