### ISSUE TITLE
Lab AZ300T03_Lab_Mod01 instructions missing config values / interface mismatch

### ISSUE THREAD

**Issue by derhoppe** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#60]
In AZ300T03_Lab_Mod01 Ex. 1 Task 1 step 2 the instructions don't seem to reflect the new wizard for creating a storage account.

**Secure transfer required: Disabled
Virtual network: All networks**

After secure transfer there are more options in the wizard which should be addressed in the lab instructions.

**Comment by polichtm** [comment]
updated
rgds
Marcin
