### ISSUE TITLE
No labs for AZ300-T06?

### ISSUE THREAD

**Issue by tiagocostapt** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#7]
Can't find any lab for AZ300-T06. I'm missing something?

**Comment by ElaMark** [comment]
I created my own exercises for most of the course. After spending a lot of time doing that I'd prefer not to see any new labs as they would now be difficult to fit in. For 300T06 it's easy to come up with all sorts of things students could do. That is of course only my opinion, everybody teaches it differently I guess.

**Comment by tiagocostapt** [comment]
I also have created my own content but doesn't make any sense to have labs in all modules expect this last one. I would prefer that Microsoft creates some content for this. Not all MCTs will have the option to create and use their content.

**Comment by molenaar** [comment]
Please, add a lab. At least one.
@ElaMark , why not contribute your labs to the community?

**Comment by ElaMark** [comment]
I don't have any step-by-step instructions written out; I tell students to _do as I do_ and we discuss what we're creating as we go along. If you want to give them step-by-step instructions why not point out the many quickstarts in the documentation let them choose one or two? I know some other trainers doing this and they report the students are very happy with it.

**Comment by polichtm** [comment]
A lab has been added
rgds
Marcin
