### ISSUE TITLE
Error and suggestion to AZ-300T02_Lab_Mod03_Configuring VNet peering and service chaining.md

### ISSUE THREAD

**Issue by tbkobberoe** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#72]
In Exercise 1 there are 2 Task 1's. Also, when deploying the second VM it will go faster if you duplicate the browser tab, open a new Azure Cloud Shell and start the deployment without having to wait for the first VM to complete. I know we are talking a few minutes, but all the time we can save in these labs are precious.

**Comment by polichtm** [comment]
Which task(s) are you referring to (in your statement about "duplicating" the browser tab)?
rgds
Marcin

**Comment by tbkobberoe** [comment]
Rask 2 pt. 2 can't be done before task 1 pt, 7 has finished unless you start a new Cloud Shell session from a new browser tab, IT says in the note after rask 1 pt, 7 that the student shoukdn't wait for the rask to finish before continuing with task 2, but that's only possible in a new session. Hope that clarifies it

**Comment by polichtm** [comment]
you can simply use --no-wait parameter - updated accordingly
rgds
Marcin
