### ISSUE TITLE
Skillpipe Text has PS commands run together

### ISSUE THREAD

**Issue by TechGeekNM** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#73]
In class today and have found that in exercise 2, Task 1, step #3, the PowerShell command is one jumbled mess, instead of the four separate commands that need to be run.

**Comment by polichtm** [comment]
Would you mind clarifying which course/module you are referring to?
rgds
Marcin

**Comment by polichtm** [comment]
Closing due to lack of response
