### ISSUE TITLE
command does not execute in L01 Module 1 Lab 1 Final Task

### ISSUE THREAD

**Issue by ccalebcarter** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#76]
Requesting a Cloud Shell.Succeeded.
Connecting terminal...

Welcome to Azure Cloud Shell

Type "az" to use Azure CLI
Type "help" to learn about Cloud Shell

caleb@Azure:~$ az group list --query "[?starts_with(name,'az300010')].[name]" --output tsv
az3000101-LabRG
caleb@Azure:~$ az group list --query "[?starts_with(name,'az300010')].[name]" --output tsv | %{az group delete -n $_ --no-wait -y}
bash: %{az: command not found
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
caleb@Azure:~$ az group list --query "[?starts_with(name,'az300010')].[name]" --output tsv | % {az group delete -n $_ --no-wait -y}
bash: %: command not found
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
caleb@Azure:~$ az group list --query "[?starts_with(name,'az300010')].[name]" --output tsv | %az group delete -n $_ --no-wait -y
bash: %az: command not found
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
caleb@Azure:~$ az group list --query "[?starts_with(name,'az300010')].[name]" --output tsv | az group delete -n $_ --no-wait -y
az group delete: error: argument --name/-n/--resource-group/-g: expected one argument
usage: az group delete [-h] [--verbose] [--debug]
                       [--output {json,jsonc,table,tsv,yaml,none}]
                       [--query JMESPATH] [--subscription _SUBSCRIPTION]
                       --name RESOURCE_GROUP_NAME [--yes] [--no-wait]
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
caleb@Azure:~$

**Comment by polichtm** [comment]
This works perfectly fine for me. 
Are you sure you are running this as a single line?
rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response
