### ISSUE TITLE
300T01_Lab_Mod05_Implementing user-assigned managed identities for Azure resources

### ISSUE THREAD

**Issue by tbkobberoe** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#77]
Why is this lab a part of the course? Managed identities is not mentioned once in the course. I can see that it's part of the exam subjects, but it hardly make sense to make a labin such a complex area without further introduction

**Comment by polichtm** [comment]
It's not clear whether you are suggesting that the lab should be removed or whether the corresponding content should be added to the course. Would you mind clarifying?
rgds
Marcin

**Comment by tbkobberoe** [comment]
The subject is being taught in AZ-300T03 module 4, but this module already has a lab regarding RBAC. My experience with doing labs that has content which hasn't been taught are not the best, but that's just my opinion. As long as the AZ-300 course is also meant to be run in single days it doesn't make sense to have a lab in day 1 which isn't taught until day 3. And also, the timing for AZ-300T01 is way off anyway, so removing the lab would help on that. Unfortunately there won't be a lab on Azure AD at all then, but that would be OK if you ask me

**Comment by polichtm** [comment]
Is there anyone else who would be interested in getting this lab removed?
rgds
Marcin

**Comment by polichtm** [comment]
Closing due to lack of response.
