### ISSUE TITLE
Please add to 

### ISSUE THREAD

**Issue by wojciehm** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#80]
Task 2: Configure HashiCorp Packer prerequisites

https://github.com/MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies/blob/master/Instructions/AZ-300T01_Lab_Mod03_Implementing%20Custom%20Azure%20VM%20Images.md

Please add either the programmatic list of Azure Regions or add command to list them using Azure Cloud Shell.

`az account list-locations -output table`

**Comment by polichtm** [comment]
updated
