### ISSUE TITLE
AZ-300T01_Lab_Mod03 packer deletes resource group

### ISSUE THREAD

**Issue by wojciehm** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#81]
In lab https://github.com/MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies/blob/master/Instructions/AZ-300T01_Lab_Mod03_Implementing%20Custom%20Azure%20VM%20Images.md#task-2-configure-hashicorp-packer-prerequisites

task 2 we are creating a new image with packer. We are suppose to create a new image and then reuse it in next task.

See my shell output, whole resource group is being deleted.

![image](https://user-images.githubusercontent.com/19718255/63030397-88cb6d00-beb2-11e9-9155-f944ceef9f88.png)

**Comment by polichtm** [comment]
Witam p. Wojciechu,
Would you mind clarifying why are you concerned about this? Are you able to complete the lab succesfully?
rgds
Marcin

**Comment by wojciehm** [comment]
Yes, it worked. Sorry for false alarm.
