### ISSUE TITLE
Lab T01 Mod 01 incomplete steps

### ISSUE THREAD

**Issue by derhoppe** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#82]
Excercise 3, Task 1 says "At the top of the portal, click the Cloud Shell icon to open the Cloud Shell pannel and **swicth t**o th**e Bash she**ll if necessary." 
Should be "PowerShell" instead, because the command is designed for PowerShell and doesn't work in Bash.

**Comment by polichtm** [comment]
These are not PowerShell cmdlets - these are Azure CLI commands meant to be run from Bash shell
What specifically is the error you are seeing?
rgds
Marcin

**Comment by derhoppe** [comment]
Hi Marcin, the error is thrown when you run the second command in this excercise. The error is

"bash: %{az: command not found"

**Comment by polichtm** [comment]
valid point - appreciate the clarification - this has been updated
rgds
Marcin
