### ISSUE TITLE
AZ300T02 Lab Module 3 - please change VM size

### ISSUE THREAD

**Issue by derhoppe** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#84]
In the azuredeploy0401.json file, an instance size of Standard_D1 is used for deploying the Windows Server Systems which is, in terms of performance, not the best option, because the lab takes way longer to complete if you are waiting for the server to get up and running or just clocking yourself through random "out of memory" messages.

Please increase the machine size in the template.

**Comment by polichtm** [comment]
Increasing the VM size is likely to increase the possibility of exceeding the corresponding vCPU quota limits. While this can obviously be remediated by requesting the increase of these limits, it's rather tough to predict how feasible that would be in every scenario. This is the reason that the VM size is defined as a template parameter - you are free to modify it to your liking at the deployment time
rgds
Marcin

**Comment by derhoppe** [comment]
Thanks for your reply. As the students are removing their existing resources after each lab, sticking to the learning material means there will be actually no other VMs in place at the deployment time - so if we are using the microsoft labs, the Core Limit will not be exceeded. 

Since we are also discussing the core limits on the first day, it would be a good learning if a student has deployed a VM and tries to deploy VMs which exceed the Core Limit.

Having a predictable Error is better than telling the students "you may have to wait a looong time, for some tasks in this lab." - just try this lab yourself and at a good chance, you will see how long it takes to login and install server roles on these VMs.

So please take this in consideration in terms of VM size.

Thanks & rgds, Sebastian

**Comment by polichtm** [comment]
Hi Sebastian
appreciate the feedback.
Our intention is to minimize potential issues that students might be running into. In this particular case, I believe there is a benefit of flexibility in scenarios where increasing the core limits might not be an option. The recommended approach to reaching this objective is to parameterize templates. 
This also facilitates your scenario where quota limit is not a factor and larger VM sizes can be used.

A comment regarding the recommended VM size might be a potential alternative - but the problem with this approach is that the availability of that particular VM size might differ across regions. Another option might be provide the recommended number of vCPUs, but that would force instructors/students to search for the VM size ;)
rgds
Marcin
