### ISSUE TITLE
AZ-300.1 Module 5 - online lab - az group deployment create

### ISSUE THREAD

**Issue by yuem99** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#90]
Please help!

I got the following: 

Failed to parse azuredeploy05.json with exception:
    Expecting value: line 7 column 1 (char 6)

when I try to run 

az group deployment create --resource-group az3000501-LabRG --template-file azuredeploy05.json --parameters @azuredeploy05.parameters.json

more info below: 
a842c589-aa91-4f53-9b95-36b50e43@Azure:~$ az group deployment create --resource-group az3000501-LabRG --template-file azuredeploy05.json --parameters @azuredeploy05.parameters.json
Failed to parse azuredeploy05.json with exception:
    Expecting value: line 7 column 1 (char 6)
a842c589-aa91-4f53-9b95-36b50e43@Azure:~$ ls
azuredeploy0401.json           azuredeploy05.json             azuredeploy0801.json             clouddrive      packer
azuredeploy04.parameters.json  azuredeploy05.parameters.json  azuredeploy0801.parameters.json  cloud-init.txt  packer_1.3.1_linux_amd64.zip

**Comment by polichtm** [comment]
This completes successfully for me.
Pls consider downloading/uploading the template/parameters file again - and make sure that you are running Bash session within Cloud Shell
If this does not resolve the issue, post the content of azuredeploy05.json
rgds
Marcin

**Comment by yuem99** [comment]
Thanks for getting back to me. I still got the same error msg "Failed to parse azuredeploy05.json with exception:
    Expecting value: line 7 column 1 (char 6)"

when running "az group deployment create --resource-group az3000501-LabRG --template-file azuredeploy05.json --parameters @azuredeploy05.parameters.json"

Here is the link to azuredeploy05.json

https://github.com/MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies/blob/master/allfiles/AZ-300T01/Module_05/azuredeploy05.json

Thanks!

**Comment by polichtm** [comment]
Pls post the output of the first four pages of the output of 
cat azuredeploy05.json | more
executed from within the Cloud Shell
rgds
Marcin

**Comment by yuem99** [comment]
I used the command "wget https://github.com/MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies/blob/master/allfiles/AZ-300T01/Module_05/azuredeploy05.json"

to upload azuredeploy05.json into azure account. Once azuredeploy05.json is in azure account, it is corrupted. 

I used azure portal to upload the json file.  Now the command "az group deployment create" works! Thanks!

Questions: 
1) what is the command to upload a github file into azure account in cloud shell? As I pointed above, "wget" does not work
2) what is the command to download a file into my local machine in cloud shell?

Thanks!

**Comment by polichtm** [comment]
Good to see that you managed to get this resolved.
wget should work - you need to make sure that you point to the raw version of the json file

https://raw.githubusercontent.com/MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies/master/allfiles/AZ-300T01/Module_05/azuredeploy05.json

rgds
Marcin
