### ISSUE TITLE
AZ300T01-M03 lab has unneeded steps

### ISSUE THREAD

**Issue by MikeBazMSFT** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#92]
As of last month, Packer now ships in Cloud Shell (https://azure.microsoft.com/en-us/updates/new-tools-in-azure-cloud-shell/), so downloading and extracting it is redundant and unnecessary, and potentially invites confusion on the student's part around why we are doing this when we don't need to any longer.

I submitted a proposed update through a pull request for this.

**Comment by polichtm** [comment]
merged
rgds
Marcin

**Comment by molenaar** [comment]
'build template03.json is not correct
should be 
packer build template03.json

**Comment by MikeBazMSFT** [comment]
ah you're right, not sure how I screwed that up.  thanks for catching it :)
