### ISSUE TITLE
Issue with AZ-300.4 Module 1 Lab Task 3 step 3

### ISSUE THREAD

**Issue by yuem99** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#94]
Got the following error msg: 
"At line:1 char:28
+ $password = 'Pa55w.rd1234' $securePassword = ConvertTo-SecureString - ...
+                            ~~~~~~~~~~~~~~~
Unexpected token '$securePassword' in expression or statement.
+ CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : UnexpectedToken"

when I ran the following command: 
$password = 'Pa55w.rd1234' $securePassword = ConvertTo-SecureString -Force -AsPlainText -String $password $aadApp30007 = New-AzureRmADApplication -DisplayName 'aadApp30007' -HomePage 'http://aadApp30007' -IdentifierUris 'http://aadApp30007' -Password $securePassword

Thanks.

**Comment by polichtm** [comment]
These is supposed to be executed on separate lines:

$password = 'Pa55w.rd1234' 

$securePassword = ConvertTo-SecureString -Force -AsPlainText -String $password 

$aadApp30007 = New-AzureRmADApplication -DisplayName 'aadApp30007' -HomePage 'http://aadApp30007' -IdentifierUris 'http://aadApp30007' -Password $securePassword

rgds
Marcin
