### ISSUE TITLE
Unable to get an Azure pass

### ISSUE THREAD

**Issue by yuem99** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#95]
I am still using the Azure pass that I got for 300.1, now the current cost is about $282. When I tried to get additional passes from 300.2/300.3/300.4, I got the following error msg:

Something went wrong
We are unable to provide an Azure pass at this time.

Thanks!

**Comment by polichtm** [comment]
Pls follow up with the same individual/organization from which you've received the original Azure Pass
rgds
Marcin
