### ISSUE TITLE
AZ300T01 Module 5 Lab: Managing Identities

### ISSUE THREAD

**Issue by begler1** [MicrosoftLearning/AZ-300-MicrosoftAzureArchitectTechnologies#97]
AZ300T01 Module 5 Lab: Managing Identities:

Ex 1   Task 3 Step 3: Choose "user assigned managed identity" from the   "Assign access to:" drop down.
--

**Comment by polichtm** [comment]
We are trying to avoid detailed click-through steps. 
Are you suggesting that "From the az3000502-LabRG - Access control (IAM) blade, assign the Owner role to the newly created user-assigned managed identity." is not clear enough?
rgds
Marcin

**Comment by begler1** [comment]
Just trying to be helpful.

**Comment by polichtm** [comment]
appreciated...
Ultimately this depends how difficult/easy it is to find the way to complete this step within the interface. 
It would be interesting to find out what has been the experience of other MCTs in this case
rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response
